[11/26/2025, 7:24:00 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:01 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:02 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:04 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:04 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:06 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,2,1,2,0
[11/26/2025, 7:24:06 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,2,1,2,0
[11/26/2025, 7:24:08 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:08 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:10 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:13 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:13 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:15 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:15 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:17 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:17 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:19 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:19 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:21 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:21 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:23 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:23 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:25 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,1,2
[11/26/2025, 7:24:25 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,1,2
[11/26/2025, 7:24:27 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:27 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:29 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:29 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:31 AM] | MAC: 00:11:22:33:44:06| Humidity: 96,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:31 AM] | MAC: 00:11:22:33:44:06| Humidity: 96,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:33 AM] | MAC: 00:11:22:33:44:06| Humidity: 96,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,2,0,0
[11/26/2025, 7:24:33 AM] | MAC: 00:11:22:33:44:06| Humidity: 96,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,2,0,0
[11/26/2025, 7:24:35 AM] | MAC: 00:11:22:33:44:06| Humidity: 96,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,2,2,0
[11/26/2025, 7:24:35 AM] | MAC: 00:11:22:33:44:06| Humidity: 96,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,2,2,0
[11/26/2025, 7:24:37 AM] | MAC: 00:11:22:33:44:06| Humidity: 97,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,1,0
[11/26/2025, 7:24:37 AM] | MAC: 00:11:22:33:44:06| Humidity: 97,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,1,0
[11/26/2025, 7:24:39 AM] | MAC: 00:11:22:33:44:06| Humidity: 97,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:39 AM] | MAC: 00:11:22:33:44:06| Humidity: 97,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:41 AM] | MAC: 00:11:22:33:44:06| Humidity: 97,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:24:41 AM] | MAC: 00:11:22:33:44:06| Humidity: 97,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:24:43 AM] | MAC: 00:11:22:33:44:06| Humidity: 98,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:43 AM] | MAC: 00:11:22:33:44:06| Humidity: 98,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:45 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:45 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:47 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:24:47 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:33 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:33 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:35 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 76,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:35 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 76,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:39 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 77,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:39 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 77,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:41 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 78,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,2,0,1
[11/26/2025, 7:25:41 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 78,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,2,0,1
[11/26/2025, 7:25:43 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 79,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:43 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 79,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:45 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 80,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,0,1,2,0
[11/26/2025, 7:25:45 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 80,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,0,1,2,0
[11/26/2025, 7:25:47 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 81,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:47 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 81,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:49 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 82,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,1,2,1
[11/26/2025, 7:25:49 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 82,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,1,2,1
[11/26/2025, 7:25:51 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 83,Humidity: 100,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:51 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 83,Humidity: 100,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:25:53 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 84,Humidity: 101,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,0,1
[11/26/2025, 7:25:53 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 84,Humidity: 101,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,0,1
[11/26/2025, 7:25:55 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 85,Humidity: 101,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:55 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 85,Humidity: 101,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:57 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 86,Humidity: 102,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:57 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 86,Humidity: 102,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:59 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 87,Humidity: 102,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:25:59 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 87,Humidity: 102,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:01 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 88,Humidity: 103,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,0
[11/26/2025, 7:26:01 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 88,Humidity: 103,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,0
[11/26/2025, 7:26:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 89,Humidity: 103,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 89,Humidity: 103,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:05 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 90,Humidity: 104,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,0,1
[11/26/2025, 7:26:05 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 90,Humidity: 104,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,0,1
[11/26/2025, 7:26:07 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 91,Humidity: 104,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:07 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 91,Humidity: 104,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:09 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 92,Humidity: 110,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:09 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 92,Humidity: 110,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 93,Humidity: 111,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 93,Humidity: 111,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:13 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 94,Humidity: 111,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,0,1
[11/26/2025, 7:26:13 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 94,Humidity: 111,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,0,1
[11/26/2025, 7:26:17 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 95,Humidity: 112,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:17 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 95,Humidity: 112,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:19 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 96,Humidity: 112,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,0,0,1
[11/26/2025, 7:26:19 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 96,Humidity: 112,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,0,0,1
[11/26/2025, 7:26:21 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 97,Humidity: 113,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:21 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 97,Humidity: 113,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:23 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 98,Humidity: 113,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:23 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 98,Humidity: 113,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:25 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 99,Humidity: 114,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,1,0,0,0
[11/26/2025, 7:26:25 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 99,Humidity: 114,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,1,0,0,0
[11/26/2025, 7:26:27 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 100,Humidity: 114,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,2,1
[11/26/2025, 7:26:27 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 100,Humidity: 114,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,2,1
[11/26/2025, 7:26:29 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 101,Humidity: 120,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:29 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 101,Humidity: 120,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:31 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 102,Humidity: 121,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:31 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 102,Humidity: 121,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:33 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 103,Humidity: 121,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,2,1
[11/26/2025, 7:26:33 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 103,Humidity: 121,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,2,1
[11/26/2025, 7:26:35 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 104,Humidity: 122,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,0,1
[11/26/2025, 7:26:35 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 104,Humidity: 122,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,0,1
[11/26/2025, 7:26:37 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 105,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,2,0
[11/26/2025, 7:26:37 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 105,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,2,0
[11/26/2025, 7:26:39 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:39 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 106,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:41 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 107,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:41 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 107,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:43 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 108,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:43 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 108,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:45 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,0,0,0
[11/26/2025, 7:26:45 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,0,0,0
[11/26/2025, 7:26:45 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 109,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:45 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 109,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:47 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:47 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:47 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 110,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:47 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 110,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:49 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:49 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 111,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,0,0
[11/26/2025, 7:26:49 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:49 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 111,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,0,0
[11/26/2025, 7:26:51 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,0,1
[11/26/2025, 7:26:51 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,0,1
[11/26/2025, 7:26:51 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 112,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,0,2,0
[11/26/2025, 7:26:51 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 112,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,0,2,0
[11/26/2025, 7:26:53 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,1,0
[11/26/2025, 7:26:53 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,1,0
[11/26/2025, 7:26:53 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 113,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:53 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 113,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:55 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:55 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:57 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,0,1
[11/26/2025, 7:26:57 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,0,1
[11/26/2025, 7:26:57 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 114,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:57 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 114,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:26:59 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:59 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:26:59 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 115,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,2,2,0,0,0
[11/26/2025, 7:26:59 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 115,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,2,2,0,0,0
[11/26/2025, 7:27:01 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:01 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:01 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 116,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:01 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 116,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:03 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,1,0
[11/26/2025, 7:27:03 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,1,0
[11/26/2025, 7:27:03 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 117,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,2,2,0,0
[11/26/2025, 7:27:03 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 117,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,2,2,0,0
[11/26/2025, 7:27:05 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:05 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:05 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 118,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,0,2
[11/26/2025, 7:27:05 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 118,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,0,2
[11/26/2025, 7:27:07 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,0,2,1,1
[11/26/2025, 7:27:07 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,0,2,1,1
[11/26/2025, 7:27:07 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 119,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,1,0,2
[11/26/2025, 7:27:07 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 119,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,1,0,2
[11/26/2025, 7:27:09 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,1,1,1,1
[11/26/2025, 7:27:09 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,1,1,1,1
[11/26/2025, 7:27:09 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 120,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:09 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 120,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:11 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,1,1
[11/26/2025, 7:27:11 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,1,1
[11/26/2025, 7:27:11 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 121,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:11 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 121,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:13 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,0,1,2
[11/26/2025, 7:27:13 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,0,1,2
[11/26/2025, 7:27:13 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 122,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,1,1
[11/26/2025, 7:27:13 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 122,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,1,1
[11/26/2025, 7:27:15 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:15 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:15 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 123,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:15 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 123,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:17 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:17 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:17 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 124,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,1,1
[11/26/2025, 7:27:17 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 124,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,1,1
[11/26/2025, 7:27:19 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:19 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:19 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 125,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:19 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 125,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:21 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,0,0
[11/26/2025, 7:27:21 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,0,0
[11/26/2025, 7:27:21 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 126,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,0,1,2
[11/26/2025, 7:27:21 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 126,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,0,1,2
[11/26/2025, 7:27:23 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:23 AM] | MAC: 00:11:22:33:44:06| Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:23 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 127,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:23 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 127,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:25 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 128,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:25 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 128,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:27 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 129,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,2,1
[11/26/2025, 7:27:27 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 129,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,2,1
[11/26/2025, 7:27:29 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 130,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:29 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 130,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:31 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 131,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:31 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 131,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:35 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 132,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,1,1,1,0
[11/26/2025, 7:27:35 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 132,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,1,1,1,0
[11/26/2025, 7:27:37 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 133,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,1,2
[11/26/2025, 7:27:37 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 133,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,1,2
[11/26/2025, 7:27:39 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 134,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,0,1
[11/26/2025, 7:27:39 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 134,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,0,1
[11/26/2025, 7:27:41 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 135,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:41 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 135,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:43 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 136,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,2,2,2,0,1
[11/26/2025, 7:27:43 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 136,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,2,2,2,0,1
[11/26/2025, 7:27:45 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 137,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:45 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 137,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:47 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 138,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:47 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 138,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:49 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 139,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,1,0,2
[11/26/2025, 7:27:49 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 139,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,1,0,2
[11/26/2025, 7:27:51 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 140,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,0
[11/26/2025, 7:27:51 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 140,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,0
[11/26/2025, 7:27:53 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 141,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,1,1,1
[11/26/2025, 7:27:53 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 141,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,1,1,1
[11/26/2025, 7:27:55 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 142,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:55 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 142,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:27:57 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 143,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:57 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 143,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:59 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 144,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:27:59 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 144,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:28:01 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 145,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:01 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 145,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 146,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,2,1
[11/26/2025, 7:28:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 146,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,2,1
[11/26/2025, 7:28:05 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 147,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:28:05 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 147,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:28:07 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 148,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:07 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 148,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:09 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 149,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,2,1
[11/26/2025, 7:28:09 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 149,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,2,1
[11/26/2025, 7:28:13 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 150,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:13 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 150,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:15 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 151,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:15 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 151,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:17 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 152,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,2,1
[11/26/2025, 7:28:17 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 152,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,2,1
[11/26/2025, 7:28:19 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 153,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,2,0
[11/26/2025, 7:28:19 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 153,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,2,0
[11/26/2025, 7:28:21 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 154,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,0,1,1
[11/26/2025, 7:28:21 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 154,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,0,1,1
[11/26/2025, 7:28:23 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 155,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:23 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 155,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:25 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 156,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:25 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 156,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:27 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 157,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:27 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 157,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:29 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 158,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,0,0
[11/26/2025, 7:28:29 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 158,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,0,0
[11/26/2025, 7:28:31 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 159,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,0,0,1
[11/26/2025, 7:28:31 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 159,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,0,0,1
[11/26/2025, 7:28:33 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 160,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:33 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 160,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:35 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 161,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:35 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 161,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:37 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 162,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,2,1,1
[11/26/2025, 7:28:37 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 162,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,2,1,1
[11/26/2025, 7:28:39 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 163,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:39 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 163,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:41 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 164,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:41 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 164,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:43 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 165,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,0,0
[11/26/2025, 7:28:43 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 165,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,0,0
[11/26/2025, 7:28:45 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 166,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:45 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 166,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:47 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 167,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:47 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 167,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:49 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 168,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:49 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 168,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:53 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 169,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:53 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 169,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:55 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 170,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:55 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 170,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:28:57 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 171,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,0
[11/26/2025, 7:28:57 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 171,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,0
[11/26/2025, 7:28:59 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 172,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,1,1,0
[11/26/2025, 7:28:59 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 172,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,1,1,0
[11/26/2025, 7:29:01 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 173,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:01 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 173,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 174,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:03 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 174,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:05 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 175,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,0,2,1
[11/26/2025, 7:29:05 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 175,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,0,2,1
[11/26/2025, 7:29:07 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 176,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,0,1,1
[11/26/2025, 7:29:07 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 176,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,0,1,1
[11/26/2025, 7:29:09 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 177,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,0,1,1
[11/26/2025, 7:29:09 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 177,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,1,0,1,1
[11/26/2025, 7:29:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 178,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 178,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:13 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 179,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:13 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 179,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:15 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 180,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,2,0,0
[11/26/2025, 7:29:15 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 180,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,2,0,0
[11/26/2025, 7:29:17 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 181,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,1,0,2
[11/26/2025, 7:29:17 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 181,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,1,0,2
[11/26/2025, 7:29:19 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 182,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:19 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 182,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:29:21 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 183,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,1,2
[11/26/2025, 7:29:21 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 183,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,1,2
[11/26/2025, 7:29:23 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 184,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:23 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 184,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:25 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 185,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:25 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 185,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:27 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 186,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,1,1,1
[11/26/2025, 7:29:27 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 186,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,1,1,1
[11/26/2025, 7:29:31 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 187,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,1,1
[11/26/2025, 7:29:31 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 187,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,1,1
[11/26/2025, 7:29:33 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 188,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:33 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 188,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:35 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 189,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:35 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 189,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:37 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 190,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,2,1,1
[11/26/2025, 7:29:37 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 190,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,2,1,1
[11/26/2025, 7:29:39 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 191,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,0
[11/26/2025, 7:29:39 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 191,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,0
[11/26/2025, 7:29:41 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 192,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,0,2
[11/26/2025, 7:29:41 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 192,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,0,2
[11/26/2025, 7:29:43 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 193,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,2,2
[11/26/2025, 7:29:43 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 193,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,2,2
[11/26/2025, 7:29:45 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 194,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,1
[11/26/2025, 7:29:45 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 194,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,1
[11/26/2025, 7:29:47 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 195,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:47 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 195,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:49 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 196,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,0,2
[11/26/2025, 7:29:49 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 196,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,0,2
[11/26/2025, 7:29:51 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 197,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,2,1,1,1
[11/26/2025, 7:29:51 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 197,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,2,1,1,1
[11/26/2025, 7:29:53 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 198,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:53 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 198,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:29:55 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 199,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,1
[11/26/2025, 7:29:55 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 199,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,1
[11/26/2025, 7:29:57 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 200,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,1,1
[11/26/2025, 7:29:57 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 200,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,1,1
[11/26/2025, 7:29:59 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 201,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,2,1
[11/26/2025, 7:29:59 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 201,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,2,1
[11/26/2025, 7:30:01 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 202,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:01 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 202,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:03 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 203,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,2,0,0,1,1
[11/26/2025, 7:30:03 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 203,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,2,0,0,1,1
[11/26/2025, 7:30:05 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 204,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,0
[11/26/2025, 7:30:05 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 204,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,0
[11/26/2025, 7:30:09 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 205,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,2,0,0,2,1
[11/26/2025, 7:30:09 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 205,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,2,0,0,2,1
[11/26/2025, 7:30:11 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 206,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:11 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 206,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:13 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 207,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,1,1
[11/26/2025, 7:30:13 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 207,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,1,1
[11/26/2025, 7:30:15 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 208,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,0,2,1,0
[11/26/2025, 7:30:15 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 208,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,0,2,1,0
[11/26/2025, 7:30:17 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 209,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,0,0,0
[11/26/2025, 7:30:17 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 209,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,0,0,0
[11/26/2025, 7:30:19 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 210,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:30:19 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 210,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:30:21 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 211,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:21 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 211,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:23 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 212,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:23 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 212,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:25 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 213,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,1,0
[11/26/2025, 7:30:25 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 213,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,1,0
[11/26/2025, 7:30:27 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 214,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:27 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 214,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:29 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 215,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:29 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 215,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:31 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 216,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:31 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 216,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:33 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 217,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,2,0
[11/26/2025, 7:30:33 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 217,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,2,0
[11/26/2025, 7:30:35 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 218,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:35 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 218,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:37 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 219,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:37 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 219,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:39 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 220,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:39 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 220,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:41 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 221,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:41 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 221,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:43 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 222,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:43 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 222,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:30:45 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 223,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,0,0
[11/26/2025, 7:30:45 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 223,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,0,0
[11/26/2025, 7:30:49 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 224,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,2,2
[11/26/2025, 7:30:49 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 224,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,2,2
[11/26/2025, 7:30:51 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 225,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,1
[11/26/2025, 7:30:51 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 225,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,1
[11/26/2025, 7:30:53 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 226,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,2,1,1,1
[11/26/2025, 7:30:53 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 226,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,2,1,1,1
[11/26/2025, 7:30:55 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 227,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,1,0
[11/26/2025, 7:30:55 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 227,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,1,0
[11/26/2025, 7:30:57 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 228,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,1
[11/26/2025, 7:30:57 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 228,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,1
[11/26/2025, 7:30:59 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 229,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:30:59 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 229,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:01 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 230,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:31:01 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 230,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:31:03 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 231,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,0,1
[11/26/2025, 7:31:03 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 231,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,0,1
[11/26/2025, 7:31:05 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 232,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:05 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 232,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:07 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 233,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:07 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 233,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:09 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 234,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:09 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 234,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:11 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 235,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:11 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 235,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:13 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 236,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,1,2
[11/26/2025, 7:31:13 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 236,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,1,2
[11/26/2025, 7:31:15 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 237,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:15 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 237,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:17 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 238,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,2,0,2,0,0
[11/26/2025, 7:31:17 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 238,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,2,0,2,0,0
[11/26/2025, 7:31:19 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 239,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,2,1
[11/26/2025, 7:31:19 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 239,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,2,1
[11/26/2025, 7:31:21 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 240,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:21 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 240,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:23 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 241,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:23 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 241,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:27 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 242,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,0,2
[11/26/2025, 7:31:27 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 242,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,0,2
[11/26/2025, 7:31:29 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 243,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:29 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 243,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:31 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 244,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:31 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 244,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:33 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 245,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,0,0,1
[11/26/2025, 7:31:33 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 245,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,1,0,0,1
[11/26/2025, 7:31:35 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 246,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,1
[11/26/2025, 7:31:35 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 246,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,1
[11/26/2025, 7:31:37 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 247,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:37 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 247,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:39 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 248,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,0,2
[11/26/2025, 7:31:39 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 248,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,0,2
[11/26/2025, 7:31:41 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 249,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:41 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 249,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:43 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 250,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:43 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 250,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:45 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 251,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,2,0,1,1
[11/26/2025, 7:31:45 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 251,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,2,0,1,1
[11/26/2025, 7:31:47 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 252,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,2,0
[11/26/2025, 7:31:47 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 252,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,2,0
[11/26/2025, 7:31:49 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 253,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:49 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 253,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:51 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 254,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:51 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 254,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:53 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 255,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,1,1
[11/26/2025, 7:31:53 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 255,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,1,1
[11/26/2025, 7:31:55 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 256,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:55 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 256,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:57 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 257,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:57 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 257,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:59 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 258,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:31:59 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 258,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:01 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 259,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,2,1,1
[11/26/2025, 7:32:01 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 259,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,2,1,1
[11/26/2025, 7:32:05 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 260,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:05 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 260,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:07 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 261,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:07 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 261,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:09 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 262,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:09 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 262,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 263,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,0,1
[11/26/2025, 7:32:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 263,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,0,1
[11/26/2025, 7:32:13 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 264,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,1,0
[11/26/2025, 7:32:13 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 264,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,1,0
[11/26/2025, 7:32:15 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 265,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:15 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 265,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:17 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 266,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,1,0,0
[11/26/2025, 7:32:17 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 266,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,1,0,0
[11/26/2025, 7:32:19 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 267,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,0,2
[11/26/2025, 7:32:19 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 267,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,0,2
[11/26/2025, 7:32:21 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 268,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:21 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 268,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:23 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 269,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:23 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 269,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:25 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 270,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:25 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 270,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:27 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 271,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,0,1
[11/26/2025, 7:32:27 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 271,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,0,1
[11/26/2025, 7:32:29 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 272,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:29 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 272,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:31 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 273,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,0
[11/26/2025, 7:32:31 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 273,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,0
[11/26/2025, 7:32:33 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 274,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,1
[11/26/2025, 7:32:33 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 274,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,1
[11/26/2025, 7:32:35 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 275,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,1,2
[11/26/2025, 7:32:35 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 275,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,1,2
[11/26/2025, 7:32:37 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 276,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,0,1
[11/26/2025, 7:32:37 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 276,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,2,0,1
[11/26/2025, 7:32:39 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 277,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,2,2
[11/26/2025, 7:32:39 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 277,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,2,2
[11/26/2025, 7:32:41 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 278,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,1,2
[11/26/2025, 7:32:41 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 278,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,1,2
[11/26/2025, 7:32:45 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 279,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:45 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 279,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:47 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 280,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:47 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 280,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:49 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 281,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,0,2,2,1
[11/26/2025, 7:32:49 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 281,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,0,2,2,1
[11/26/2025, 7:32:51 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 282,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:51 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 282,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:53 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 283,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:53 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 283,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:32:55 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 284,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,0,0
[11/26/2025, 7:32:55 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 284,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,2,0,0
[11/26/2025, 7:32:57 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 285,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,1,1
[11/26/2025, 7:32:57 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 285,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,1,1
[11/26/2025, 7:32:59 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 286,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,2,1
[11/26/2025, 7:32:59 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 286,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,0,2,1
[11/26/2025, 7:33:01 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 287,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:01 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 287,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:03 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 288,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,1,2,0
[11/26/2025, 7:33:03 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 288,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,1,2,0
[11/26/2025, 7:33:05 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 289,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,2,1,1
[11/26/2025, 7:33:05 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 289,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,2,1,1
[11/26/2025, 7:33:07 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 290,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,0,1
[11/26/2025, 7:33:07 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 290,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,0,1
[11/26/2025, 7:33:09 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 291,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,2,0,0
[11/26/2025, 7:33:09 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 291,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,2,0,0
[11/26/2025, 7:33:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 292,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,0,1
[11/26/2025, 7:33:11 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 292,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,0,1
[11/26/2025, 7:33:13 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 293,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:33:13 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 293,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:33:15 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 294,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,1,1,1,2
[11/26/2025, 7:33:15 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 294,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,1,1,1,2
[11/26/2025, 7:33:17 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 295,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,1,2
[11/26/2025, 7:33:17 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 295,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,1,2
[11/26/2025, 7:33:19 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 296,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:33:19 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 296,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:33:23 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 297,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,2,0
[11/26/2025, 7:33:23 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 297,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,2,0
[11/26/2025, 7:33:25 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 298,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,1,1
[11/26/2025, 7:33:25 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 298,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,1,1
[11/26/2025, 7:33:27 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 299,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:27 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 299,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:29 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 300,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,0,0,1,1
[11/26/2025, 7:33:29 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 300,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,0,0,1,1
[11/26/2025, 7:33:31 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 301,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,2,1
[11/26/2025, 7:33:31 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 301,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,2,1
[11/26/2025, 7:33:33 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 302,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:34 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 302,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:35 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 303,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,0,0
[11/26/2025, 7:33:35 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 303,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,0,0
[11/26/2025, 7:33:37 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 304,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:37 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 304,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:39 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 305,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,0
[11/26/2025, 7:33:40 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 305,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,0
[11/26/2025, 7:33:42 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 306,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:42 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 306,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:44 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 307,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:44 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 307,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:46 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 308,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:46 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 308,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:33:48 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 309,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,1,2,0
[11/26/2025, 7:33:48 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 309,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,1,2,0
[11/26/2025, 7:33:50 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 310,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,2,0,0,1,1
[11/26/2025, 7:33:50 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 310,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,2,0,0,1,1
[11/26/2025, 7:33:52 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 311,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,2,0,1,0
[11/26/2025, 7:33:52 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 311,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,2,0,1,0
[11/26/2025, 7:33:54 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 312,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,2,0,1
[11/26/2025, 7:33:54 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 312,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,2,2,0,1
[11/26/2025, 7:33:56 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 313,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,1,2,0
[11/26/2025, 7:33:56 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 313,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,1,2,0
[11/26/2025, 7:33:58 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 314,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,1,2
[11/26/2025, 7:33:58 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 314,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,1,2
[11/26/2025, 7:34:02 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 315,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:02 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 315,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:04 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 316,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:04 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 316,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:06 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 317,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:06 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 317,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:08 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 318,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,1,2
[11/26/2025, 7:34:08 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 318,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,0,1,1,2
[11/26/2025, 7:34:10 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 319,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,1,2,0,0
[11/26/2025, 7:34:10 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 319,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,1,2,0,0
[11/26/2025, 7:34:12 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 320,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:12 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 320,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:14 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 321,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,1,2
[11/26/2025, 7:34:14 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 321,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,1,1,2
[11/26/2025, 7:34:16 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 322,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,0,0
[11/26/2025, 7:34:16 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 322,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,0,0
[11/26/2025, 7:34:18 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 323,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,1,0
[11/26/2025, 7:34:18 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 323,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,1,0
[11/26/2025, 7:34:20 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 324,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:20 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 324,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:22 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 325,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,1,0
[11/26/2025, 7:34:22 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 325,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,1,0
[11/26/2025, 7:34:24 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 326,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,2,0,1,1
[11/26/2025, 7:34:24 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 326,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,2,0,1,1
[11/26/2025, 7:34:26 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 327,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,1,1
[11/26/2025, 7:34:26 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 327,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,1,1,1,1
[11/26/2025, 7:34:28 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 328,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,0,1
[11/26/2025, 7:34:28 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 328,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,0,1
[11/26/2025, 7:34:30 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 329,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:30 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 329,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:32 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 330,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:32 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 330,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:34:34 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 331,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,1,1
[11/26/2025, 7:34:34 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 331,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,1,1
[11/26/2025, 7:34:36 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 332,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,1,0
[11/26/2025, 7:34:36 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 332,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,0,1,1,0
[11/26/2025, 7:34:38 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 333,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:38 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 333,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:42 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 334,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,1,2
[11/26/2025, 7:34:42 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 334,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,0,1,2
[11/26/2025, 7:34:44 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 335,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:44 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 335,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:46 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 336,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,0
[11/26/2025, 7:34:46 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 336,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,0,0
[11/26/2025, 7:34:48 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 337,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:48 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 337,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:50 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 338,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,1,1,1,1
[11/26/2025, 7:34:50 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 338,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,1,1,1,1
[11/26/2025, 7:34:52 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 339,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,1,0,0,1
[11/26/2025, 7:34:52 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 339,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,2,1,0,0,1
[11/26/2025, 7:34:54 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 340,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,1,2
[11/26/2025, 7:34:54 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 340,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,1,2
[11/26/2025, 7:34:56 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 341,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:56 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 341,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:58 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 342,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:34:58 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 342,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:00 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 343,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,0,1,0
[11/26/2025, 7:35:00 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 343,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,0,0,1,0
[11/26/2025, 7:35:02 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 344,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,0,1,2,1
[11/26/2025, 7:35:02 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 344,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,0,1,2,1
[11/26/2025, 7:35:04 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 345,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:04 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 345,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:06 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 346,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:06 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 346,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:08 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 347,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,0,1
[11/26/2025, 7:35:08 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 347,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,0,1
[11/26/2025, 7:35:10 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 348,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,2
[11/26/2025, 7:35:10 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 348,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,2,1,0,2
[11/26/2025, 7:35:12 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 349,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:12 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 349,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:14 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 350,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,1,0
[11/26/2025, 7:35:14 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 350,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,1,0
[11/26/2025, 7:35:16 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 351,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:16 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 351,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:20 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 352,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,1,0
[11/26/2025, 7:35:20 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 352,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,1,0
[11/26/2025, 7:35:22 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 353,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:22 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 353,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:24 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 354,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:24 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 354,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:26 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 355,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:26 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 355,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:28 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 356,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:28 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 356,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:30 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 357,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,1,2
[11/26/2025, 7:35:30 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 357,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,1,2
[11/26/2025, 7:35:32 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 358,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:32 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 358,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:34 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 359,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:34 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 359,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:36 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 360,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:35:36 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 360,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:35:38 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 361,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,0,0
[11/26/2025, 7:35:38 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 361,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,1,0,0
[11/26/2025, 7:35:40 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 362,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,2,0
[11/26/2025, 7:35:40 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 362,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,0,2,0
[11/26/2025, 7:35:42 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 363,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:42 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 363,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:44 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 364,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,0
[11/26/2025, 7:35:44 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 364,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,0
[11/26/2025, 7:35:46 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 365,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,0,2,1,2
[11/26/2025, 7:35:46 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 365,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,0,0,2,1,2
[11/26/2025, 7:35:48 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 366,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:48 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 366,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:50 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 367,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:50 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 367,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:35:52 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 368,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,2,1,2
[11/26/2025, 7:35:52 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 368,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 0,1,1,2,1,2
[11/26/2025, 7:35:54 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 369,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:54 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 369,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:58 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 370,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:35:58 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 370,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:00 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 371,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,1,0,2,1
[11/26/2025, 7:36:00 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 371,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,1,0,2,1
[11/26/2025, 7:36:02 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 372,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,2,0,1
[11/26/2025, 7:36:02 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 372,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,2,0,1
[11/26/2025, 7:36:04 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 373,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,1,0,2
[11/26/2025, 7:36:04 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 373,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,1,0,1,0,2
[11/26/2025, 7:36:06 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 374,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:06 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 374,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:08 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 375,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,0,1
[11/26/2025, 7:36:08 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 375,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,2,0,1
[11/26/2025, 7:36:10 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 376,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:10 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 376,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:12 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 377,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,1,1
[11/26/2025, 7:36:12 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 377,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,2,1,1
[11/26/2025, 7:36:14 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 378,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:14 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 378,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:16 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 379,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:16 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 379,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:18 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 380,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,0,0,1,1
[11/26/2025, 7:36:18 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 380,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 2,1,0,0,1,1
[11/26/2025, 7:36:20 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 381,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,2,1
[11/26/2025, 7:36:20 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 381,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,1,0,2,1
[11/26/2025, 7:36:22 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 382,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:22 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 382,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:24 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 383,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:24 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 383,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:26 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 384,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:26 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 384,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:28 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 385,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,0
[11/26/2025, 7:36:28 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 385,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,1,0
[11/26/2025, 7:36:30 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 386,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,2,1,0,2
[11/26/2025, 7:36:30 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 386,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,2,1,0,2
[11/26/2025, 7:36:32 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 387,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,1,1,1,2
[11/26/2025, 7:36:32 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 387,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 0,0,1,1,1,2
[11/26/2025, 7:36:34 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 388,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:34 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 388,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:36:38 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 389,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:38 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 389,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:40 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 390,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,0
[11/26/2025, 7:36:40 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 390,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,0
[11/26/2025, 7:36:42 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 391,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,0,0
[11/26/2025, 7:36:42 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 391,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,2,0,0,0
[11/26/2025, 7:36:44 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 392,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,1,2
[11/26/2025, 7:36:44 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 392,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,1,2
[11/26/2025, 7:36:46 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 393,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,2,1
[11/26/2025, 7:36:46 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 393,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,2,1
[11/26/2025, 7:36:48 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 394,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,1,2
[11/26/2025, 7:36:48 AM] | MAC: 00:11:22:33:44:05| Inside Temperature: 394,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,1,1,0,1,2
[11/26/2025, 7:36:50 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 395,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,2,0
[11/26/2025, 7:36:50 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 395,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,1,0,1,2,0
[11/26/2025, 7:36:52 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 396,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,1,2
[11/26/2025, 7:36:52 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 396,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,0,0,1,2
[11/26/2025, 7:36:54 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 397,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:54 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 397,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:56 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 398,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:56 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 398,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:36:58 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 399,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,1,2,0
[11/26/2025, 7:36:58 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 399,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,0,1,1,2,0
[11/26/2025, 7:37:00 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 400,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:00 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 400,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:02 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 401,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:02 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 401,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:04 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 402,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:04 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 402,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:06 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 403,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:06 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 403,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:08 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 404,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,0,2
[11/26/2025, 7:37:08 AM] | MAC: 00:11:22:33:44:09| Inside Temperature: 404,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,0,2
[11/26/2025, 7:37:10 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 405,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:10 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 405,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:12 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 406,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,2,0
[11/26/2025, 7:37:12 AM] | MAC: 00:11:22:33:44:08| Inside Temperature: 406,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 1,0,1,0,2,0
[11/26/2025, 7:37:16 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 407,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,1,1,0,1
[11/26/2025, 7:37:16 AM] | MAC: 00:11:22:33:44:06| Inside Temperature: 407,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 0,2,1,1,0,1
[11/26/2025, 7:37:18 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 408,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:18 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 408,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:20 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 409,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,0,0,1
[11/26/2025, 7:37:20 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 409,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,0,0,1
[11/26/2025, 7:37:22 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 410,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:22 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 410,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:24 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 411,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,1
[11/26/2025, 7:37:24 AM] | MAC: 00:11:22:33:44:00| Inside Temperature: 411,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,0,2,0,1
[11/26/2025, 7:37:26 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 412,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,0,0
[11/26/2025, 7:37:26 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 412,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,1,2,1,0,0
[11/26/2025, 7:37:28 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 413,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,1,1,0
[11/26/2025, 7:37:28 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 413,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Door Alarm,Lock Alarm | Fan Status: 2,0,0,1,1,0
[11/26/2025, 7:37:30 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 414,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:30 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 414,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:32 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 415,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,2,0,1,1
[11/26/2025, 7:37:32 AM] | MAC: 00:11:22:33:44:07| Inside Temperature: 415,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,2,0,1,1
[11/26/2025, 7:37:34 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 416,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:37:34 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 416,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,0,1,1,1
[11/26/2025, 7:37:36 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 417,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:36 AM] | MAC: 00:11:22:33:44:01| Inside Temperature: 417,Input Voltage: 1.02,Output Voltage: 1.01,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:38 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 418,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:38 AM] | MAC: 00:11:22:33:44:04| Inside Temperature: 418,Input Voltage: 1.02,Output Voltage: 1.01,Water Logging Alarm,Water Leakage Alarm,Door Alarm,Lock Alarm
[11/26/2025, 7:37:40 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 419,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,2,0,2,1
[11/26/2025, 7:37:40 AM] | MAC: 00:11:22:33:44:03| Inside Temperature: 419,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm | Fan Status: 1,2,2,0,2,1
[11/26/2025, 7:37:42 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 420,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
[11/26/2025, 7:37:42 AM] | MAC: 00:11:22:33:44:02| Inside Temperature: 420,Input Voltage: 1.02,Output Voltage: 1.01,Door Alarm,Lock Alarm
